### PR TITLE
Fix - ADF-662 Stabilize fileSelector and filePreviewer

### PR DESCRIPTION
**Pull request by 404passionFruit**
Jira https://oat-sa.atlassian.net/browse/ADF-662

Related PR https://github.com/oat-sa/tao-core/pull/3085

* hasClass is not a function in fileSelector - Fix for regression from https://github.com/oat-sa/tao-core-ui-fe/pull/344
* disable select button in filePreviewer for cases when a user doesnt have rights to select

### CODE REVIEW

**Review by clagosarias — APPROVED** [review]

**Review by habemuscode — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master
- [x]  Pull request title and description are meaningful
- [x]  Commits are following conventional commits
- [x]  Kitchen links are not exposed in the description

**Comment by AntonNeviarouski** [comment]
QA verified on http://test-shpran.playground.kitchen.it.taocloud.org:41481/

**Comment by AntonNeviarouski** [comment]
QA verified on http://test-shpran.playground.kitchen.it.taocloud.org:41481/
